# Generated by Django 3.2 on 2021-04-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('adminuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.adminuser')),
            ],
            options={
                'verbose_name_plural': 'Bloggers',
            },
            bases=('blog.adminuser',),
        ),
    ]
